/**
 * Creating a sidebar enables you to:
 - create an organized menu on a page
 - have sets of docs that appear in your NavBar
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Organize documentation by modules with auto-generated chapters
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-module-1-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo)',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02-module-2-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI & Perception (Isaac)',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '03-module-3-ai-perception',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Voice Control & Autonomy',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04-module-4-voice-control',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 5: Capstone Project',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '05-capstone-project',
        },
      ],
    },
  ],
};

module.exports = sidebars;
